# Principal Components (PCA)
with Singualr Value Decomposition (SVD)

In [7]:
from sklearn.datasets.samples_generator import make_moons
from sklearn.decomposition import PCA

/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [18]:
pca = PCA(n_components=2)

In [19]:
X, y = make_moons(n_samples=100, noise=0.05)
X2D = pca.fit_transform(X)

In [13]:
pca.components_.T[:,0]

array([ 0.94902282, -0.31520738])

In [15]:
pca.components_[0,:]

array([ 0.94902282, -0.31520738])

In [14]:
pca.componentss_

array([[ 0.94902282, -0.31520738],
       [ 0.31520738,  0.94902282]])

In [10]:
pca.explained_variance_

array([0.80860016, 0.18742797])

In [11]:
pca.explained_variance_ratio_

array([0.81182462, 0.18817538])

In [28]:
from sklearn.datasets import load_iris
iris = load_iris()
X = iris['data']
pca = PCA(n_components=4)
pca.fit_transform(X)
pca.components_

array([[ 0.36138659, -0.08452251,  0.85667061,  0.3582892 ],
       [ 0.65658877,  0.73016143, -0.17337266, -0.07548102],
       [-0.58202985,  0.59791083,  0.07623608,  0.54583143],
       [-0.31548719,  0.3197231 ,  0.47983899, -0.75365743]])

In [31]:
pca.explained_variance_

array([4.22824171, 0.24267075, 0.0782095 , 0.02383509])