In [17]:
import pandas as pd
import numpy as np

## Series

In [2]:
obj = pd.Series([4,7,8,9,-5])
obj

0    4
1    7
2    8
3    9
4   -5
dtype: int64

In [3]:
obj.values

array([ 4,  7,  8,  9, -5])

In [4]:
obj.value_counts

<bound method IndexOpsMixin.value_counts of 0    4
1    7
2    8
3    9
4   -5
dtype: int64>

In [5]:
obj.index

RangeIndex(start=0, stop=5, step=1)

In [15]:
obj2 = pd.Series([4,7,-8,-9], index=['a', 'b', 'c', 'd'])
obj2[obj2>0]*2

a     8
b    14
dtype: int64

In [8]:
obj2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [10]:
obj2['b']

7

In [12]:
obj2[['a', 'd']]

a    4
d    9
dtype: int64

In [19]:
np.exp(obj2[obj2<0])

c    0.000335
d    0.000123
dtype: float64

In [20]:
'b' in obj2

True

In [21]:
1 in obj

True

In [22]:
100 in obj


False

In [24]:
#creating pandas Series by passing the dict:
sdata= {'Ohio':35000, 'Texas':43000, 'Oregon':16000,'Utah':5000}
sdata

{'Ohio': 35000, 'Texas': 43000, 'Oregon': 16000, 'Utah': 5000}

In [26]:
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     43000
Oregon    16000
Utah       5000
dtype: int64

In [28]:
states = ['Cali', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4

Cali          NaN
Ohio      35000.0
Oregon    16000.0
Texas     43000.0
dtype: float64

In [29]:
pd.isnull(obj4)

Cali       True
Ohio      False
Oregon    False
Texas     False
dtype: bool

In [31]:
obj3

Ohio      35000
Texas     43000
Oregon    16000
Utah       5000
dtype: int64

In [32]:
obj4

Cali          NaN
Ohio      35000.0
Oregon    16000.0
Texas     43000.0
dtype: float64

In [33]:
obj3+obj4

Cali          NaN
Ohio      70000.0
Oregon    32000.0
Texas     86000.0
Utah          NaN
dtype: float64

In [34]:
obj3.name = 'population'
obj4.index.name = 'state'


In [35]:
obj3

Ohio      35000
Texas     43000
Oregon    16000
Utah       5000
Name: population, dtype: int64

In [36]:
obj4

state
Cali          NaN
Ohio      35000.0
Oregon    16000.0
Texas     43000.0
dtype: float64

In [37]:
obj

0    4
1    7
2    8
3    9
4   -5
dtype: int64

In [41]:
obj.index = ['Bob', 'Steve', 'Mike', 'John', 'Poll']

In [42]:
obj

Bob      4
Steve    7
Mike     8
John     9
Poll    -5
dtype: int64

## Dataframe

In [46]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
       'year':[2000, 2001, 2002, 2001, 2002, 2003],
       'pop':[1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [47]:
frame.head(2)

state  year  pop
0  Ohio  2000  1.5
1  Ohio  2001  1.7

In [48]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [50]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'])
frame2

year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [60]:
frame2.index =['o', 't', 'three', 'f', 'five', 'six']

In [52]:
frame2['state']

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [53]:
frame2.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [61]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt     16.5
Name: three, dtype: object

In [64]:
frame2['debt'] =16.5
frame2

year   state  pop  debt
o      2000    Ohio  1.5  16.5
t      2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
f      2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [66]:
frame2['debt'] = np.arange(6.)
frame2

year   state  pop  debt
o      2000    Ohio  1.5   0.0
t      2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
f      2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [67]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
o      2000    Ohio  1.5   NaN
t      2001    Ohio  1.7   NaN
three  2002    Ohio  3.6   NaN
f      2001  Nevada  2.4   NaN
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [70]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
o      2000    Ohio  1.5   NaN     True
t      2001    Ohio  1.7   NaN     True
three  2002    Ohio  3.6   NaN     True
f      2001  Nevada  2.4   NaN    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [80]:
del frame2['eastern']
frame2

KeyError: 'eastern'

In [81]:
pop = {'Nevada':{2001:2.4, 2002:2.9},
      'Ohio':{2000:1.5, 2001:1.7, 2002:3.6}}

frame3 = pd.DataFrame(pop)
frame3.reset_index()
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [82]:
frame2.T

o     t three       f    five     six
year   2000  2001  2002    2001    2002    2003
state  Ohio  Ohio  Ohio  Nevada  Nevada  Nevada
pop     1.5   1.7   3.6     2.4     2.9     3.2
debt    NaN   NaN   NaN     NaN    -1.7     NaN

In [84]:
frame3.index.name ='year'; frame3.columns.name = 'state'

In [85]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [86]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [87]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

## Index Objects

In [89]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
obj

a    0
b    1
c    2
dtype: int64

In [92]:
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [93]:
index[1:]

Index(['b', 'c'], dtype='object')

In [94]:
index[1]

'b'

In [95]:
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [97]:
obj2 = pd.Series([1, -2, 0], index=labels)
obj2

0    1
1   -2
2    0
dtype: int64

In [99]:
obj2.index == labels

array([ True,  True,  True])

In [100]:
obj2.index is labels

True

In [101]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [102]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [104]:
'Ohio' in frame3

True

In [107]:
2003 in frame3.index

False

In [108]:
2002 in frame3.index

True

In [109]:
#Unlike Python sets, a pandas Index can contain duplicate labels:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

# Essential Functionality
## Reindexing

In [114]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d','b','a','c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [116]:
obj2 = obj.reindex(['a','b','c','d','e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [119]:
obj3  = pd.Series(['blue', 'purple', 'yellow'], index=[0,2,4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [125]:
obj3.reindex(range(6), method='ffill').copy()

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [126]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [129]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),
                    index=['a', 'c', 'd'],
                    columns=['Ohio', 'Texas', 'California'])

frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [130]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [131]:
states = ['Texas', 'Utah', 'California']
frame.reindex(columns = states)
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8